// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: helloworld.proto

#include "helloworld.pb.h"
#include "helloworld.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace rpc_package {

static const char* AddService_method_names[] = {
  "/rpc_package.AddService/myAdd",
};

std::unique_ptr< AddService::Stub> AddService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AddService::Stub> stub(new AddService::Stub(channel, options));
  return stub;
}

AddService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_myAdd_(AddService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AddService::Stub::myAdd(::grpc::ClientContext* context, const ::rpc_package::DataRequest& request, ::rpc_package::DataReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rpc_package::DataRequest, ::rpc_package::DataReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_myAdd_, context, request, response);
}

void AddService::Stub::async::myAdd(::grpc::ClientContext* context, const ::rpc_package::DataRequest* request, ::rpc_package::DataReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rpc_package::DataRequest, ::rpc_package::DataReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_myAdd_, context, request, response, std::move(f));
}

void AddService::Stub::async::myAdd(::grpc::ClientContext* context, const ::rpc_package::DataRequest* request, ::rpc_package::DataReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_myAdd_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rpc_package::DataReply>* AddService::Stub::PrepareAsyncmyAddRaw(::grpc::ClientContext* context, const ::rpc_package::DataRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rpc_package::DataReply, ::rpc_package::DataRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_myAdd_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rpc_package::DataReply>* AddService::Stub::AsyncmyAddRaw(::grpc::ClientContext* context, const ::rpc_package::DataRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncmyAddRaw(context, request, cq);
  result->StartCall();
  return result;
}

AddService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AddService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AddService::Service, ::rpc_package::DataRequest, ::rpc_package::DataReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AddService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rpc_package::DataRequest* req,
             ::rpc_package::DataReply* resp) {
               return service->myAdd(ctx, req, resp);
             }, this)));
}

AddService::Service::~Service() {
}

::grpc::Status AddService::Service::myAdd(::grpc::ServerContext* context, const ::rpc_package::DataRequest* request, ::rpc_package::DataReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace rpc_package

